packages:
  - playground
  - packages/**

catalog:
  '@material/material-color-utilities': ^0.3.0
  '@rushstack/eslint-patch': ^1.8.0
  '@types/node': ^22.5.0
  '@unocss/core': ^0.62.0
  '@unocss/preset-mini': ^0.62.0
  '@unocss/reset': ^0.62.0
  '@unocss/vite': ^0.62.0
  '@vitejs/plugin-vue': ^5.0.0
  '@vue/eslint-config-prettier': ^9.0.0
  '@vue/eslint-config-typescript': ^3.0.0
  '@vue/tsconfig': ^0.5.0
  'bumpp': ^9.5.0
  'eslint': ^8.57.0
  'eslint-plugin-vue': ^9.23.0
  'prettier': ^3.2.5
  'typescript': ^5.6.0
  'unbuild': ^2.0.0
  'unocss': latest
  'vitest': ^2.0.0
  'vite': ^5.3.0
  'vue': ^3.4.0
  'vue-tsc': ^2.0.0
